apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.name }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "platform.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: {{ .Values.postgres.image }}
          command: ["sh", "-c", "until pg_isready -h {{ .Values.postgres.name }} -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB; do echo waiting; sleep 2; done"]
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.name }}-secret
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Values.api.name }}-config
            - secretRef:
                name: {{ .Values.postgres.name }}-secret
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            {{- toYaml .Values.api.probes.startup | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            {{- toYaml .Values.api.probes.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /db-check
              port: 8000
            {{- toYaml .Values.api.probes.readiness | nindent 12 }}