apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.name }}-config
data:
  APP_ENV: {{ .Values.env | quote }}
  SERVICE_NAME: {{ .Values.api.name | quote }}
  DB_HOST: {{ .Values.postgres.name | quote }}
  DB_PORT: "5432"